package com.example.atlas.telegram;

public enum TelegramAction {
    OPEN_MAIN_MENU,
    GO_BACK,
    CONTINUE_FLOW,
    RESTART_FLOW,
    CONFIRM_ACTION,
    DECLINE_ACTION,
    START_ONBOARDING,
    SHOW_DAY_PLAN,
    START_CHECKIN,
    START_HABITS,
    START_EVENING,
    SHOW_WEEKLY_REPORT,
    START_QUESTION,
    OPEN_SETTINGS,
    SHOW_HELP,
    CANCEL_FLOW,
    SHOW_EMERGENCY_PLAN,
    OPEN_PROFILE,
    CONFIRM_RESTART_ONBOARDING,
    RESTART_ONBOARDING,
    CHANGE_LANGUAGE,
    SELECT_LANGUAGE_RU,
    SELECT_LANGUAGE_EN
}
